import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { useEffect } from 'react';
import Table from '../components/Table';
import RandomCode from '../RandomCode';

export default function Home() {
  const prevCode = RandomCode();
  const [rows, setRows] = useState([]);
  const [isRunRandom, setIsRunRandom] = useState(false);
  const soLuongCode = 676000;
  const soKyTuCode = 9
  const giaTriCode = 'ABCDEFGHIJKLMNPQRSTUVWXYZ123456789'
  const soKyTuSeri = 6;
  const giaTriSeri = '0123456789'

  function handleClick() {
    if (!isRunRandom) {
      setIsRunRandom( isRunRandom => true );
    }
  }

  function handleChange() {
    console.log('Change')
  }

  useEffect(() => {
    setRows(rows => [...prevCode]);
    console.log(rows)
  }, []);

useEffect(() => {
  if (rows.length > 0) {
    setIsRunRandom(isRunRandom => true);
  }
  
},[rows])

useEffect(() => {
    if (isRunRandom && rows.length < soLuongCode) {
      runRandom();
    }
    
    async function runRandom() {
      let code = await runRandomUniqueValue(soKyTuCode, giaTriCode, 'code');
      let seri = await runRandomUniqueValue(soKyTuSeri, giaTriSeri, 'seri');
      let row = { code, seri };
      setRows(rows => [...rows, row]);
      setIsRunRandom(isRunRandom => false);
    }
    
    async function runRandomUniqueValue(soKyTu, giaTri, type) {
      const result = new Promise( (resolve, reject) => {
        let randomNumber = runRandomValue(soKyTu, giaTri);
        while ( isIncluded(randomNumber, type) ) {
          randomNumber = runRandomValue(soKyTu, giaTri);
        }
        resolve(randomNumber)
      })
      return result;
      }
  
      function isIncluded(randomNummber, type) {
        if (rows.some(item => { return item[type] == randomNummber })) {
          return true
        } else {
          return false
        }
      }

      function runRandomValue(soKyTu, giaTri) {
        var result           = '';
        var characters       = giaTri;
        var charactersLength = characters.length;
        for ( var i = 0; i < soKyTu; i++ ) {
          result += characters.charAt(Math.floor(Math.random() * 
     charactersLength));
       }
       return result;
    }


}, [isRunRandom, rows]) 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          A An Random: <a href="https://nextjs.org">{rows.length}</a>
        </h1>
      <button onClick={handleClick}>Start random</button>
      <Table className={styles.ul} rows={rows} onChange={handleChange}>
      </Table>
      </main>
</div>
  )  
}
